CREATE TABLE IF NOT EXISTS CITY (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(40)
);
CREATE TABLE IF NOT EXISTS USER (
    id SERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(40) UNIQUE,
    password VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS ITINERARY (
    id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(40),
    creator INTEGER REFERENCES USERS(id),
    time VARCHAR(40),
    price VARCHAR(40),
    activities VARCHAR(40),
    hashtags VARCHAR(40) [3],
    city_id INTEGER NOT NULL REFERENCES CITIES(id)
);